# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui\main.ui'
#
# Created: Thu Feb 28 09:20:26 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(725, 422)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(250, 250))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 725, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuView = QtGui.QMenu(self.menuBar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        MainWindow.setMenuBar(self.menuBar)
        self.dockWidget_2 = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_2.sizePolicy().hasHeightForWidth())
        self.dockWidget_2.setSizePolicy(sizePolicy)
        self.dockWidget_2.setMinimumSize(QtCore.QSize(250, 400))
        self.dockWidget_2.setMaximumSize(QtCore.QSize(250, 400))
        self.dockWidget_2.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget_2.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget_2.setObjectName(_fromUtf8("dockWidget_2"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.dockWidgetContents_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.toolButton_2 = QtGui.QToolButton(self.dockWidgetContents_2)
        self.toolButton_2.setMinimumSize(QtCore.QSize(30, 30))
        self.toolButton_2.setMaximumSize(QtCore.QSize(30, 30))
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.buttonGroup = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.toolButton_2)
        self.gridLayout_2.addWidget(self.toolButton_2, 0, 2, 1, 1)
        self.toolButton_8 = QtGui.QToolButton(self.dockWidgetContents_2)
        self.toolButton_8.setMinimumSize(QtCore.QSize(30, 30))
        self.toolButton_8.setMaximumSize(QtCore.QSize(30, 30))
        self.toolButton_8.setObjectName(_fromUtf8("toolButton_8"))
        self.buttonGroup.addButton(self.toolButton_8)
        self.gridLayout_2.addWidget(self.toolButton_8, 2, 2, 1, 1)
        self.toolButton_9 = QtGui.QToolButton(self.dockWidgetContents_2)
        self.toolButton_9.setMinimumSize(QtCore.QSize(30, 30))
        self.toolButton_9.setMaximumSize(QtCore.QSize(30, 30))
        self.toolButton_9.setObjectName(_fromUtf8("toolButton_9"))
        self.buttonGroup.addButton(self.toolButton_9)
        self.gridLayout_2.addWidget(self.toolButton_9, 2, 3, 1, 1)
        self.toolButton_10 = QtGui.QToolButton(self.dockWidgetContents_2)
        self.toolButton_10.setMinimumSize(QtCore.QSize(30, 30))
        self.toolButton_10.setMaximumSize(QtCore.QSize(30, 30))
        self.toolButton_10.setObjectName(_fromUtf8("toolButton_10"))
        self.gridLayout_2.addWidget(self.toolButton_10, 0, 4, 1, 1)
        self.toolButton_7 = QtGui.QToolButton(self.dockWidgetContents_2)
        self.toolButton_7.setMinimumSize(QtCore.QSize(30, 30))
        self.toolButton_7.setMaximumSize(QtCore.QSize(30, 30))
        self.toolButton_7.setObjectName(_fromUtf8("toolButton_7"))
        self.buttonGroup.addButton(self.toolButton_7)
        self.gridLayout_2.addWidget(self.toolButton_7, 2, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 5, 1, 1)
        self.toolButton = QtGui.QToolButton(self.dockWidgetContents_2)
        self.toolButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setMinimumSize(QtCore.QSize(30, 30))
        self.toolButton.setMaximumSize(QtCore.QSize(30, 30))
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.buttonGroup.addButton(self.toolButton)
        self.gridLayout_2.addWidget(self.toolButton, 0, 1, 1, 1)
        self.toolButton_3 = QtGui.QToolButton(self.dockWidgetContents_2)
        self.toolButton_3.setMinimumSize(QtCore.QSize(30, 30))
        self.toolButton_3.setMaximumSize(QtCore.QSize(30, 30))
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.buttonGroup.addButton(self.toolButton_3)
        self.gridLayout_2.addWidget(self.toolButton_3, 0, 3, 1, 1)
        self.toolButton_6 = QtGui.QToolButton(self.dockWidgetContents_2)
        self.toolButton_6.setMinimumSize(QtCore.QSize(30, 30))
        self.toolButton_6.setMaximumSize(QtCore.QSize(30, 30))
        self.toolButton_6.setObjectName(_fromUtf8("toolButton_6"))
        self.buttonGroup.addButton(self.toolButton_6)
        self.gridLayout_2.addWidget(self.toolButton_6, 1, 3, 1, 1)
        self.toolButton_4 = QtGui.QToolButton(self.dockWidgetContents_2)
        self.toolButton_4.setMinimumSize(QtCore.QSize(30, 30))
        self.toolButton_4.setMaximumSize(QtCore.QSize(30, 30))
        self.toolButton_4.setObjectName(_fromUtf8("toolButton_4"))
        self.buttonGroup.addButton(self.toolButton_4)
        self.gridLayout_2.addWidget(self.toolButton_4, 1, 1, 1, 1)
        self.toolButton_5 = QtGui.QToolButton(self.dockWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_5.sizePolicy().hasHeightForWidth())
        self.toolButton_5.setSizePolicy(sizePolicy)
        self.toolButton_5.setMinimumSize(QtCore.QSize(30, 70))
        self.toolButton_5.setMaximumSize(QtCore.QSize(30, 70))
        self.toolButton_5.setFocusPolicy(QtCore.Qt.TabFocus)
        self.toolButton_5.setObjectName(_fromUtf8("toolButton_5"))
        self.gridLayout_2.addWidget(self.toolButton_5, 1, 4, 2, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.comboBox = QtGui.QComboBox(self.dockWidgetContents_2)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.comboBox)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_2)
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionDummy = QtGui.QAction(MainWindow)
        self.actionDummy.setObjectName(_fromUtf8("actionDummy"))
        self.actionQuit_2 = QtGui.QAction(MainWindow)
        self.actionQuit_2.setObjectName(_fromUtf8("actionQuit_2"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionTollbox = QtGui.QAction(MainWindow)
        self.actionTollbox.setObjectName(_fromUtf8("actionTollbox"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit_2)
        self.menuFile.addAction(self.actionQuit)
        self.menuView.addAction(self.actionTollbox)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QObject.connect(self.actionTollbox, QtCore.SIGNAL(_fromUtf8("activated()")), self.dockWidget_2.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.label.setText(_translate("MainWindow", "ROOM#", None))
        self.toolButton_2.setText(_translate("MainWindow", "N", None))
        self.toolButton_2.setShortcut(_translate("MainWindow", "8", None))
        self.toolButton_8.setText(_translate("MainWindow", "S", None))
        self.toolButton_8.setShortcut(_translate("MainWindow", "2", None))
        self.toolButton_9.setText(_translate("MainWindow", "SE", None))
        self.toolButton_9.setShortcut(_translate("MainWindow", "3", None))
        self.toolButton_10.setText(_translate("MainWindow", "-", None))
        self.toolButton_10.setShortcut(_translate("MainWindow", "-", None))
        self.toolButton_7.setText(_translate("MainWindow", "SW", None))
        self.toolButton_7.setShortcut(_translate("MainWindow", "1", None))
        self.toolButton.setText(_translate("MainWindow", "NW", None))
        self.toolButton.setShortcut(_translate("MainWindow", "7", None))
        self.toolButton_3.setText(_translate("MainWindow", "NE", None))
        self.toolButton_3.setShortcut(_translate("MainWindow", "9", None))
        self.toolButton_6.setText(_translate("MainWindow", "E", None))
        self.toolButton_6.setShortcut(_translate("MainWindow", "6", None))
        self.toolButton_4.setText(_translate("MainWindow", "W", None))
        self.toolButton_4.setShortcut(_translate("MainWindow", "4", None))
        self.toolButton_5.setText(_translate("MainWindow", "+", None))
        self.toolButton_5.setShortcut(_translate("MainWindow", "+", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "Walk", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "Create", None))
        self.actionNew.setText(_translate("MainWindow", "New", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave_As.setText(_translate("MainWindow", "Save As", None))
        self.actionDummy.setText(_translate("MainWindow", "Dummy", None))
        self.actionQuit_2.setText(_translate("MainWindow", "Quit", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionTollbox.setText(_translate("MainWindow", "Tollbox", None))

