"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['MudMapper.py']
DATA_FILES = ['ui']
OPTIONS = {'argv_emulation': True,
 'iconfile': '/Users/thornag/Development/projects/tf-mapper/version4/ui/icons/hychsohn.icns','includes': ['sip', 'PyQt4._qt']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
